Feature#imexportexcel
dromara/hertzbeat pull request #879
Opened 2023-04-13 16:30 UTC by zqr10159

## What's changed?

[manager]import and export by excel via `ExcelImExportServiceImpl.java`
tips:. The request parameter needs to use type:=Excel.
todo:The front-end doesn't have an Excel version, and I hope someone can make it.

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

2023-04-13 16:32 UTC, zqr10159 commented
#862

2023-04-16 04:52 UTC, zqr10159 commented
@gcdd1993 @tomsun28 Please help me review these,thanks

2023-04-17 03:37 UTC, gcdd1993 requested changes

2023-04-17 03:37 UTC, gcdd1993 commented on manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AbstractImExportServiceImpl.java
> +        log.info("exportMonitor.monitor{}",exportMonitor.monitor);
日志之间需要空格分割

2023-04-17 03:37 UTC, gcdd1993 commented on manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AbstractImExportServiceImpl.java
> +        log.info("exportMonitor.monitor{}",exportMonitor.monitor);
日志级别最好修改为debug

2023-04-17 03:37 UTC, gcdd1993 commented on manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/ExcelImExportServiceImpl.java
> +    private static String getCellValueAsString(Cell cell) {
应该不需要使用static方法

2023-04-18 01:37 UTC, gcdd1993 approved these changes

2023-04-18 06:39 UTC, merged