[manager]import and export by YAML via YamlImExportServiceImpl.java
dromara/hertzbeat pull request #896
Opened 2023-04-20 17:04 UTC by zqr10159

tips:. The request parameter needs to use type:=YAML. todo:The front-end doesn't have an YAML version, and I hope someone can make it.

## What's changed?

[manager]import and export by YAML via YamlImExportServiceImpl.java
tips:. The request parameter needs to use type:=YAML.
todo:The front-end doesn't have an YAML version, and I hope someone can make it.

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

2023-04-21 01:44 UTC, gcdd1993 requested changes

2023-04-21 01:44 UTC, gcdd1993 commented on manager/src/main/java/org/dromara/hertzbeat/manager/config/YamlMapperConfig.java
> +        return new ObjectMapper().registerModule(new JavaTimeModule());
可以直接`@Bean new JavaTimeModule()`，使项目默认`ObjectMapper`注册`JavaTimeModule`

2023-04-21 01:44 UTC, gcdd1993 commented on manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/YamlImExportServiceImpl.java
> +            objectMapper.writeValue(os, monitorList);
这是不是写错了？这不还是JSON吗

2023-04-21 03:32 UTC, zqr10159 commented on manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/YamlImExportServiceImpl.java
> +            objectMapper.writeValue(os, monitorList);
没写错，上面用qualified注解指定了yamlconfig，导出就是yaml，已经经过测试

2023-04-21 03:36 UTC, zqr10159 commented on manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/YamlImExportServiceImpl.java
> +            objectMapper.writeValue(os, monitorList);
这里new忘记删了，我改一下

2023-04-21 06:01 UTC, gcdd1993 requested changes

2023-04-21 06:01 UTC, gcdd1993 commented on manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/YamlImExportServiceImpl.java
> +            objectMapper.writeValue(os, monitorList);
那建议修改下变量名为`yamlMapper`

2023-04-21 06:01 UTC, gcdd1993 commented on manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/YamlImExportServiceImpl.java
> +    private YamlImExportServiceImpl(ObjectMapper yamlMapper) {
这里没看到哪里使用到了

2023-04-21 07:05 UTC, zqr10159 commented on manager/src/main/java/org/dromara/hertzbeat/manager/config/YamlMapperConfig.java
> +        return new ObjectMapper().registerModule(new JavaTimeModule());
这个我试了不行哎，还是会报错，目前这样写可以

2023-04-21 07:15 UTC, zqr10159 commented on manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/YamlImExportServiceImpl.java
> +    private YamlImExportServiceImpl(ObjectMapper yamlMapper) {
下面用到了，objectmapper和yamlmapper不分开会导致全局都在使用yamlmapper，返回的json都是错的

2023-04-21 09:38 UTC, gcdd1993 commented on manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/YamlImExportServiceImpl.java
> +    private YamlImExportServiceImpl(YAMLMapper yamlMapper) {
这个构造器似乎没什么用？

2023-04-21 13:41 UTC, zqr10159 commented on manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/YamlImExportServiceImpl.java
> +    private YamlImExportServiceImpl(YAMLMapper yamlMapper) {
是的，之前因为obejctmapper写的，这个要删掉

2023-04-21 14:58 UTC, zqr10159 commented
#862

2023-04-21 14:59 UTC, hertzbeat commented
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
#862

2023-04-22 08:01 UTC, gcdd1993 approved these changes

2023-04-22 08:21 UTC, merged